""""" VIM CONFIGURATION """""

"My remaps
let mapleader=" "
nnoremap Q ZQ
noremap <leader><leader> :set relativenumber!<CR>
command! W execute 'w !sudo tee % > /dev/null' <bar> edit!

"Window next, buffer next, delete and vsplit
noremap <leader>n <C-w>w
noremap <leader>b :bn<CR>
noremap <leader>x :bd<CR>
noremap <leader>v :vnew<CR>

"FZF settings
let g:fzf_vim = {}
let g:fzf_vim.command_prefix = 'Fzf'
nnoremap <A-a> :FzfBLines<CR>
nnoremap <A-s> :FzfLines<CR>
nnoremap <A-d> :FzfFiles<CR>
nnoremap <A-f> :FzfHistory<CR>
nnoremap <A-g> :FzfRg<CR>
nnoremap <A-u> :FzfBuffers<CR>
nnoremap <A-c> :FzfChanges<CR>
nnoremap <A-m> :FzfMarks<CR>
nnoremap <A-j> :FzfJumps<CR>
nnoremap <A-.> :FzfHistory:<CR>
nnoremap <A-,> :FzfHistory/<CR>

"Cursor look and bg render fix
let &t_SI = "\e[6 q"
let &t_SR = "\e[3 q"
let &t_EI = "\e[2 q"
let &t_ut=''

"My settings
set background=dark   
colorscheme wildcharm
syntax on
filetype plugin indent on
set nu cul autoread hidden
set title titlestring=%F
set ruler rulerformat=%43(\ \ %v\ \ \ %l/%L\ \ %p%%%=\ \%)
set directory=~/Public/
set ignorecase smartcase incsearch
set mouse=a scrolloff=5
set spelllang=cs,en
set softtabstop=4 shiftwidth=4 expandtab

"Statusline and custom background    
hi StatusLine ctermbg=0 ctermfg=22
hi Normal ctermbg=234  
hi NonText ctermbg=234
hi LineNr ctermbg=234   
hi cursorline ctermbg=235   

"Plugins
call plug#begin()
    Plug 'tpope/vim-commentary'
    Plug 'Konfekt/filepicker.vim'
    Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
    Plug 'junegunn/fzf.vim'
call plug#end()

""""" END OF FILE """""
